language: cpp

before_install:
  - sudo add-apt-repository -y ppa:h-rayflood/llvm
  - sudo apt-get update -qq
  - sudo apt-get install --allow-unauthenticated -qq libboost-dev clang-3.3 clang-3.3-dev python-pip
  - sudo pip install lit

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build

script:
  - cmake -DCMAKE_CXX_COMPILER=clang++-3.3 ..
  - make all check
